# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  #vmImage: 'windows-latest'
  name: "MujahidQA"
  Agent.Name: "MujahidVM"

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Start-Process -Verb RunAs C:\Users\devrpvm-user\Documents\PSUnitTest\ps.bat'

